export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const USERLIST_START = 'USERLIST_START'
export const USERLIST_SUCCESS = 'USERLIST_SUCCESS'
export const USERLIST_FAIL = 'USERLIST_FAIL'

export const USERDETAIL_START = 'USERDETAIL_START'
export const USERDETAIL_SUCCESS = 'USERDETAIL_SUCCESS'
export const USERDETAIL_FAIL = 'USERDETAIL_FAIL'

export const PROJECTURL_START = 'PROJECTURL_START'
export const PROJECTURL_SUCCESS = 'PROJECTURL_SUCCESS'
export const PROJECTURL_FAIL = 'PROJECTURL_FAIL'


export const PROJECTURL_CREATE_START = 'PROJECTURL_CREATE_START'
export const PROJECTURL_CREATE_SUCCESS = 'PROJECTURL_CREATE_SUCCESS'
export const PROJECTURL_CREATE_FAIL = 'PROJECTURL_CREATE_FAIL'

export const PROJECTURL_DELETE_START = 'PROJECTURL_DELETE_START'
export const PROJECTURL_DELETE_SUCCESS = 'PROJECTURL_DELETE_SUCCESS'
export const PROJECTURL_DELETE_FAIL = 'PROJECTURL_DELETE_FAIL'

export const PROJECTURL_ITEM_CREATE_START = 'PROJECTURL_ITEM_CREATE_START'
export const PROJECTURL_ITEM_CREATE_SUCCESS = 'PROJECTURL_ITEM_CREATE_SUCCESS'
export const PROJECTURL_ITEM_CREATE_FAIL = 'PROJECTURL_ITEM_CREATE_FAIL'

export const PROJECTURL_ITEM_DELETE_START = 'PROJECTURL_ITEM_DELETE_START'
export const PROJECTURL_ITEM_DELETE_SUCCESS = 'PROJECTURL_ITEM_DELETE_SUCCESS'
export const PROJECTURL_ITEM_DELETE_FAIL = 'PROJECTURL_ITEM_DELETE_FAIL'





export const BLOG_LIST_START = 'BLOG_LIST_START'
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL'


export const BLOG_DETAIL_START = 'BLOG_DETAIL_START'
export const BLOG_DETAIL_SUCCESS = 'BLOG_DETAIL_SUCCESS'
export const BLOG_DETAIL_FAIL = 'BLOG_DETAIL_FAIL'

export const BLOG_DELETE_START = 'BLOG_DELETE_START'
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS'
export const BLOG_DELETE_FAIL = 'BLOG_DELETE_FAIL'

export const BLOG_UPDATE_START = 'BLOG_UPDATE_START'
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS'
export const BLOG_UPDATE_FAIL = 'BLOG_UPDATE_FAIL'

export const BLOG_CREATE_START = 'BLOG_CREATE_START'
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS'
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL'

export const BLOG_CREATE_COMMENT_START = 'BLOG_CREATE_COMMENT_START'
export const BLOG_CREATE_COMMENT_SUCCESS = 'BLOG_CREATE_COMMENT_SUCCESS'
export const BLOG_CREATE_COMMENT_FAIL = 'BLOG_CREATE_COMMENT_FAIL'






