# Generated by Django 3.0.3 on 2020-10-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200823_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_subject', models.CharField(max_length=50)),
                ('contact_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_subject', models.CharField(max_length=50)),
                ('contact_message', models.TextField()),
                ('to_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
