# Generated by Django 3.0.3 on 2020-10-15 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200823_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturlitems',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
