# Generated by Django 3.0.3 on 2020-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201015_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturlitems',
            name='name',
            field=models.CharField(default='helllo thsi si the name', max_length=50),
            preserve_default=False,
        ),
    ]
