# Generated by Django 3.0.3 on 2020-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projecturlitems_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturl',
            name='appbar_color',
            field=models.CharField(choices=[('primaryColor', 'primaryColor'), ('warningColor', 'warningColor'), ('dangerColor', 'dangerColor'), ('successColor', 'successColor'), ('infoColor', 'infoColor'), ('roseColor', 'roseColor'), ('grayColor', 'grayColor')], default='primaryColor', max_length=50),
        ),
    ]
